name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i --frozen-lockfile
      - run: bun run prepare
      - run: bun run typecheck
      - run: bun run lint
      - run: bun run build
